const userSchema=  {
        type:'object',
        required:[
            'name','last_name','username','email','password'
        ],
        properties:{
            name:{
                type:'string',
                min:3,
                max:25
            },
            last_name:{
                type:'string',
                min:3,
                max:25
            },
            username:{
                type:'string',
                min: 3,
                max: 20,
                unique:true
            },
            email:{
                type:'string',
                max: 50,
                unique:true
            },
            password:{
                type:'string',
                min:60
            },
            profilePicture:{
                type:'string',
                nullable:true,
                default:''
            },
            coverPicture:{
                type:'string',
                nullable:true,
                default:''
            },
            followers:{
                type:'array',
                nullable:true,
                default:[]
            },
            following:{
                type:'array',
                nullable:true,
                default:[]
            },
            isAdmin:{
                type:'boolean',
                nullable:true,
                default:false
            },
            description:{
                type:'string',
                nullable:true,
                maximum:50
            },
            city:{
                type:'string',
                nullable:true,
                max:50
            },
            from:{
                type:'string',
                nullable:true,
                max:50
            },
            relationship:{
                type:'number',
                nullable:true,
                enum:[1,2,3]
            },
            created_at:{
                type:'string',
                default: new Date
            },
            updated_at:{
                type:'string',
                default: new Date
            }
        }
}
const userSchemaPut=  {
        type:'object',
        required:[
            'name','last_name','username','email'
        ],
        properties:{
            name:{
                type:'string',
                min:3,
                max:25
            },
            last_name:{
                type:'string',
                min:3,
                max:25
            },
            username:{
                type:'string',
                min: 3,
                max: 20,
                unique:true
            },
            email:{
                type:'string',
                max: 50,
                unique:true
            },
            password:{
                type:'string',
                min:60
            },
            profilePicture:{
                type:'string',
                nullable:true,
                default:''
            },
            coverPicture:{
                type:'string',
                nullable:true,
                default:''
            },
            followers:{
                type:'array',
                nullable:true,
                default:[]
            },
            following:{
                type:'array',
                nullable:true,
                default:[]
            },
            isAdmin:{
                type:'boolean',
                nullable:true,
                default:false
            },
            description:{
                type:'string',
                nullable:true,
                maximum:50
            },
            city:{
                type:'string',
                nullable:true,
                max:50
            },
            from:{
                type:'string',
                nullable:true,
                max:50
            },
            relationship:{
                type:'number',
                nullable:true,
                enum:[1,2,3]
            },
            updated_at:{
                type:'string',
                default: new Date
            }
        }
}
module.exports = {userSchema,userSchemaPut}